spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&connectTimeout=3000&socketTimeout=1000
    username: root           # 需要学员自己修改填写
    password: twp19931226         # 需要学员自己修改填写
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    #配置类读写下面的
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: wjf # 登录druid的账号
    druidPassword: wjf # 登录druid的密码
    cachePrepStmts: true  # 开启二级缓存

  redis:
    host: 192.168.235.133
    port: 6379
    #      cluster:
    #         max-redirects: 3
    #         nodes: 127.0.0.1:7000,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005 
    #      lettuce:
    #         pool:
    #            max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
    #            max.idle: 10   # 连接池中的最大空闲连接
    #            min-idle: 5 # 连接池中的最小空闲连接
    #            max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制
    timeout: 6000ms
    password:
    database: 0
mybatis:
  typeAliasesPackage: com.weapon.mobileredis.mapper      # 需要学员自己修改填写
  mapperLocations: classpath:/com/weapon/mobileredis/mapper/*.xml
  configLocation: classpath:/mybatis-config.xml
  mapperScanPackage: com.weapon.mobileredis.mapper #配置类读写这个